const activitiesData = [
  {
    activity: "Stretching",
    id: 1,
    description: "Lorem ipsum dolor sit consectetur.",
    image: require("../../assets/images/activities/stretching-100.png"),
    duration: 1,
    finish: 0,
    calories: 525,
  },
  {
    activity: "Walking",
    id: 2,
    image: require("../../assets/images/activities/walking-100.png"),
    description: "Lorem ipsum dolor sit consectetur.",
    duration: 0.1,
    finish: 0,
    calories: 25,
  },
  {
    activity: "Yoga",
    id: 3,
    description: "Lorem ipsum dolor sit consectetur.",
    image: require("../../assets/images/activities/yoga-100.png"),
    duration: 0.1,
    finish: 0,
    calories: 25,
  },
  {
    activity: "Meditation",
    id: 4,
    description: "Lorem ipsum dolor sit consectetur.",
    image: require("../../assets/images/activities/meditation-100.png"),
    duration: "15",
    finish: 0,
    calories: 25,
  },
  {
    activity: "Jogging",
    id: 5,
    description: "Lorem ipsum dolor sit consectetur.",
    image: require("../../assets/images/activities/jogging-100.png"),
    duration: 30,
    finish: 0,
    calories: 21,
  },
  {
    activity: "Dancing",
    id: 6,
    description: "Lorem ipsum dolor sit consectetur.",
    image: require("../../assets/images/activities/dancing-100.png"),
    duration: "15",
    finish: 0,
    calories: 21,
  },
  {
    activity: "Cleaning",
    id: 7,
    description: "Lorem ipsum dolor sit consectetur.",
    image: require("../../assets/images/activities/cleaning-100.png"),
    duration: 30,
    finish: 0,
    calories: 21,
  },
  {
    activity: "Reading",
    id: 8,
    description: "Lorem ipsum dolor sit consectetur.",
    image: require("../../assets/images/activities/reading-100.png"),
    duration: 30,
    finish: 0,
    calories: 21,
  },
];

export default activitiesData;
